TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
# EVG setup
DB += evgXL15.db
DB += evgIN20.db
# EVR setup
# Test stands
DB += evrXL05.db
DB += evrXL09.db
DB += evrXL16.db
DB += IOC-IN20-RF01Testevr.db
# Laser Room
DB += IOC-LR20-LS01evr.db
# Injector
DB += IOC-IN20-AM01evr.db
DB += IOC-IN20-BP01evr.db
DB += IOC-IN20-BP02evr.db
DB += IOC-IN20-IM01evr.db
DB += IOC-IN20-LS11evr.db
DB += IOC-IN20-LS12evr.db
DB += IOC-IN20-LS13evr.db
DB += IOC-IN20-LS14evr.db
DB += IOC-IN20-LS15evr.db
DB += IOC-IN20-LS16evr.db
DB += IOC-IN20-LS17evr.db
DB += IOC-IN20-LS18evr.db
DB += IOC-IN20-LS19evr.db
DB += IOC-IN20-MG01evr.db
DB += IOC-IN20-MP01evr.db
DB += IOC-IN20-PM01evr.db
DB += IOC-IN20-PM02evr.db
DB += IOC-IN20-PM03evr.db
DB += IOC-IN20-PM04evr.db
DB += IOC-IN20-PM05evr.db
DB += IOC-IN20-PM06evr.db
DB += IOC-IN20-PM07evr.db
DB += IOC-IN20-RF01evr.db
DB += IOC-IN20-WS01evr.db
# Sector 21
DB += IOC-LI21-BL01evr.db
DB += IOC-LI21-BP01evr.db
DB += IOC-LI21-MG01evr.db
DB += IOC-LI21-PM01evr.db


include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
include $(TOP)/configure/RULES.Db


