TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this

# EVG setup
DB += evg.db
DB += evgEvent.db
DB += evgXL15.template
DB += evgIN20.template
# EVR setup
DB += evr.db
DB += evrEvent.db
DB += evrEventRate.db
# Test stands
DB += evrXL05.template
DB += evrXL09.template
DB += evrXL16.template
# Laser Room
DB += IOC-LR20-LS01evr.template
# Injector
DB += IOC-IN20-AM01evr.template  
DB += IOC-IN20-BP01evr.template  
DB += IOC-IN20-BP02evr.template  
DB += IOC-IN20-IM01evr.template  
DB += IOC-IN20-LS11evr.template  
DB += IOC-IN20-LS12evr.template  
DB += IOC-IN20-LS13evr.template  
DB += IOC-IN20-LS14evr.template  
DB += IOC-IN20-LS15evr.template  
DB += IOC-IN20-LS16evr.template  
DB += IOC-IN20-LS17evr.template  
DB += IOC-IN20-LS18evr.template  
DB += IOC-IN20-LS19evr.template  
DB += IOC-IN20-MG01evr.template  
DB += IOC-IN20-MP01evr.template
DB += IOC-IN20-PM01evr.template
DB += IOC-IN20-PM02evr.template
DB += IOC-IN20-PM03evr.template
DB += IOC-IN20-PM04evr.template
DB += IOC-IN20-PM05evr.template
DB += IOC-IN20-PM06evr.template
DB += IOC-IN20-PM07evr.template
DB += IOC-IN20-RF01evr.template
DB += IOC-IN20-WS01evr.template
# Sector 21
DB += IOC-LI21-BL01evr.template
DB += IOC-LI21-BP01evr.template
DB += IOC-LI21-MG01evr.template
DB += IOC-LI21-PM01evr.template


include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
include $(TOP)/configure/RULES.Db


