TOP=../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
#
DB += evrPatternProc.db
# Test stands
DB += evrPatternXL05.db
DB += evrPatternXL09.db
DB += evrPatternXL16.db
#DB += IOC-IN20-EV02pattern.db
DB += bsaXL01.db
DB += bsaSimXL01.db
DB += bsaXL02.db
DB += bsaSimXL02.db
DB += bsaXL03.db
DB += bsaSimXL03.db
DB += bsaXL04.db
DB += bsaSimXL04.db
DB += bsaXL05.db
DB += bsaSimXL05.db
DB += bsaXL09.db
DB += bsaSimXL09.db
# Laser Room
DB += IOC-LR20-LS01pattern.db
# Pattern Injector
DB += IOC-IN20-AM01pattern.db  
DB += IOC-IN20-BP01pattern.db  
DB += IOC-IN20-BP02pattern.db  
DB += IOC-IN20-IM01pattern.db  
DB += IOC-IN20-LS11pattern.db  
DB += IOC-IN20-LS12pattern.db  
DB += IOC-IN20-LS13pattern.db  
DB += IOC-IN20-LS14pattern.db  
DB += IOC-IN20-LS15pattern.db  
DB += IOC-IN20-LS16pattern.db  
DB += IOC-IN20-LS17pattern.db  
DB += IOC-IN20-LS18pattern.db  
DB += IOC-IN20-LS19pattern.db  
DB += IOC-IN20-MG01pattern.db  
DB += IOC-IN20-MP01pattern.db
DB += IOC-IN20-PM01pattern.db
DB += IOC-IN20-PM02pattern.db
DB += IOC-IN20-PM03pattern.db
DB += IOC-IN20-PM04pattern.db
DB += IOC-IN20-PM05pattern.db
DB += IOC-IN20-PM06pattern.db
DB += IOC-IN20-PM07pattern.db
DB += IOC-IN20-RF01pattern.db
DB += IOC-IN20-MC01pattern.db
# Pattern Sector 21
DB += IOC-LI21-BL01pattern.db
DB += IOC-LI21-BP01pattern.db
DB += IOC-LI21-MG01pattern.db
DB += IOC-LI21-PM01pattern.db

# BSA Injector
DB += IOC-IN20-BP01bsa.db
DB += IOC-IN20-BP02bsa.db
DB += IOC-IN20-IM01bsa.db
DB += IOC-IN20-RF01bsa.db
DB += IOC-IN20-MC01bsa.db

# BSA Sector 21
DB += IOC-LI21-BL01bsa.db
DB += IOC-LI21-BP01bsa.db
DB += IOC-LI21-MC01bsa.db
DB += IOC-LI21-RF01bsa.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
include $(TOP)/configure/RULES.Db


