#  -*- Makefile -*-
TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

# EDM Screens to install
EDLS += evr.edl
EDLS += evrTrig3T.edl

# Install images to be used by EDM (Gif and Png are supported)
# PNG is better and preferred.
#PNGS +=
#GIFS +=

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
