TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
#

# Rules for installing ChannelWatcher files:
RESTORE += evrDevTrig.cwConfig
RESTORE += evrIocTrig.cwConfig
RESTORE += evrPMXXTrig.cwConfig
RESTORE += evrTrig.req.template


include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

